config/routes.rb
Rails.application.routes.draw do
  put '/user_notif/:id', to: 'user_notif/notifs#read', as: :read_user_notif
  devise_for :users, controllers: { confirmations: 'users/confirmations',
                                    registrations: 'users/registrations' }

  devise_scope :user do
    patch '/confirm' => 'users/confirmations#confirm'
  end

  post '/user/preform', to: 'users#preform', as: :user_preform
  post '/user/check_cards', to: 'users#check_card', as: :user_check_card
  post '/user/check_credentials', to: 'users#check_credentials', as: :user_check_credentials

  authenticated :user do
    root to: 'locations#index', as: :authenticated_root

    post 'locations/:id/inline_update', to: 'locations#inline_update', as: :location_inline_update

    resources :locations do
      resources :offer_reductions
    end

    resources :offer_reductions
    resources :businesses
    resources :cards
    resources :users
  end

  root 'home#index', as: :root

  require 'sidekiq/web'

  # TODO: Change autorizations
  #authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  #end
end

app/models/user.rb
# A User is .. a user :)
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar, styles: { medium: '300x300>', thumb: '100x100>' }, default_url: 'default/user_avatar.png'
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/, size: { in: 0..2.megabytes }

  has_many :notifs, class_name: 'UserNotif::Notif'
  has_many :cards
  accepts_nested_attributes_for :cards

  validates_presence_of :cards
  validates :email, presence: true, uniqueness: true

  after_create :add_complete_notif

  # Whether or not the password is required.
  #
  # Only after account confirmation.
  def password_required?
    confirmed? ? super : false
  end

  # Linked to progressive engagement (See ConfirmationsController)
  def password_match?
    self.errors[:password] << 'can\'t be blank' if password.blank?
    self.errors[:password_confirmation] << 'can\'t be blank' if password_confirmation.blank?
    self.errors[:password_confirmation] << 'does not match password' if password != password_confirmation
    password == password_confirmation && !password.blank?
  end

  # Returns the user full name
  def full_name
    "#{first_name} #{last_name}"
  end

  # Returns the user profile completion percentage
  def completion_percentage
    fields = %w(first_name last_name address postal_code city country birthday phone_number avatar.present? )
    sum_add = 100.0 / fields.count
    fields.inject(0) { |sum, field| sum + (field.split('.').inject(self) { |us, o| us.send(o) }.blank? ? 0 : sum_add) }.round.to_i
  end

  # Returns the user offers ordered by location
  def offers_by_location
    offers = {}
    self.cards.each do |card|
      offers[card.location.name] = card.location.offer_reductions
    end
    offers
  end

  private

  # Creates the UserProfileCompletionNotif
  def add_complete_notif
    UserFormProgressNotif.create(user: self, target: self, sticky: true, unread: true)
  end
end

app/controllers/users/confirmations_controller.rb
# Handles the requests about users confirmations
#
# It overrides Devise controller to customize its behaviour
class Users::ConfirmationsController < Devise::ConfirmationsController
  # Devise code
  def show
    self.resource = resource_class.find_by_confirmation_token(params[:confirmation_token]) if params[:confirmation_token].present?
    super if resource.nil? or resource.confirmed?
  end

  # Devise code
  def confirm
    self.resource = resource_class.find_by_confirmation_token(params[resource_name][:confirmation_token]) if params[resource_name][:confirmation_token].present?
    if resource.update_attributes(permitted_params) && resource.password_match?
      self.resource = resource_class.confirm_by_token(params[resource_name][:confirmation_token])
      set_flash_message :notice, :confirmed
      sign_in_and_redirect(resource_name, resource)
    else
      render action: 'show'
    end
  end

  private

  # Filters the permitted params
  def permitted_params
    params.require(resource_name).permit(:confirmation_token, :password, :password_confirmation)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# Handles the requests about users omniauth callbacks
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# Handles the requests about users passwords
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# Handles the requests about users registations
class Users::RegistrationsController < Devise::RegistrationsController
  # Creates a user without password but with a card object assigned
  #
  # POST /resource
  def create
    ## Custom Code - BEGIN
    card = Card.where(uid: params[:user][:cards_attributes][:uid], user: nil)
    flash[:error] = t('errors.card.inexistent') unless card
    build_resource(sign_up_params)
    resource.cards << card if card
    resource.save
    ## Custom Code - END
    ## Devise code - BEGIN
    if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message! :notice, :signed_up
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      @errors = resource.errors.messages.values.flatten
      render 'home/index'
    end
    ## Devise code - END
  end

  private

  # Filters the permitted params
  def sign_up_params
    params.require(:user).permit(:email, cards_attributes: [:id])
  end
end

app/controllers/users/sessions_controller.rb
# Handles requests about users sessions
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# Handles requests about users unlocks
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
# Handles requests about users
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :ensure_user_has_rights, only: [:show, :edit, :update, :destroy]

  # Lists all users
  #
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # Displays the details of a user
  #
  # GET /users/1
  # GET /users/1.json
  def show
  end

  # Display a form to create a new user
  #
  # GET /users/new
  def new
    @user = User.new
  end

  # Display a form to edit an existing user
  #
  # GET /users/1/edit
  def edit
  end

  # Creates a new user from params
  #
  # Authorized parameters: :email, :first_name, :last_name, :address, :postal_code, :city, :phone_number
  #
  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if params[:user][:cards_attributes]
        cards = []
        params[:user][:cards_attributes].each do |_, v|
          card = Card.where(uid: v[:uid]).first
          cards << card if card && v[:_destroy] == 'false'
        end
        @user.cards = cards.uniq
      end
      if @user.save
        format.html { redirect_to @user, notice: t('user.create.success') }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # Updates an existing user from params
  #
  # Authorized parameters: :email, :first_name, :last_name, :address, :postal_code, :city, :phone_number
  #
  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if params[:user][:cards_attributes]
        cards = []
        params[:user][:cards_attributes].each do |_, v|
          card = Card.where(uid: v[:uid]).first
          cards << card if card && v[:_destroy] == 'false'
        end
        @user.cards = cards.uniq
      end
      if @user.update(user_params)
        format.html { redirect_to @user, notice: t('user.update.success') }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # Destroys a user
  #
  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: t('user.destroy.success') }
      format.json { head :no_content }
    end
  end

  # Will replace the form on homepage
  #
  # Try to find an existing user
  #
  # POST /user/preform
  def preform
    @user = User.find_by(email: params[:email]) || User.new(email: params[:email])
    render partial: @user.persisted? ? 'form_password' : 'form_card_uid'
  end

  # Checks if card is valid and not associated to a use
  #
  # POST /user/check_cards
  def check_card
    @card = Card.where(uid: params[:card], user_id: nil).first
    if @card
      head :ok
    else
      head :forbidden
    end
  end

  # Checks if credentials are valids
  #
  # POST /user/check_credentials
  def check_credentials
    @user = User.where(email: params[:email]).first
    if @user && @user.valid_password?(params[:password])
      head :ok
    else
      head :unauthorized
    end
  end

  private

  # Ensures user has access to the resource
  #
  # TODO: Limit access
  def ensure_user_has_rights
    redirect_to root_path unless current_user
  end

  # Sets the user object required by the action
  def set_user
    @user = User.find(params[:id])
  end

  # Filter the permitted params
  def user_params
    params.fetch(:user, {}).permit(:email, :first_name, :last_name, :address,
                                   :postal_code, :city, :phone_number, :avatar)
  end
end

app/helpers/users_helper.rb
# Helpers relative to a User
module UsersHelper
end

app/views/users/_card_fields.html.erb
<div class="nested-fields">
  <%= f.input :uid %>
  <%= link_to_remove_association t('card.remove'), f %>
</div>

app/views/users/_form.html.erb
<%= simple_form_for(user) do |f| %>
    <% if user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(user.errors.count, 'error') %> prohibited this user from being saved:</h2>

          <ul>
            <% user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="right lspace-r">
      <%= render 'progress_bar' %>
    </div>
    <div>
      <div>
        <%= image_tag 'default/info.png', class: 'left title-icon' %>
        <h3><%= t('user.profile.title') %></h3>
      </div>

      <div class="fieldset">
        <!--TODO: Email-->
        <div class="field">
          <%= f.input :first_name %>
        </div>
        <div class="field">
          <%= f.input :last_name %>
        </div>
        <div class="field">
          <%= f.input :birthday, as: :string %>
        </div>
      </div>
      <div class="fieldset">
        <div class="field">
          <%= f.input :address %>
        </div>
        <div class="field">
          <%= f.input :postal_code %>
        </div>
        <div class="field">
          <%= f.input :city %>
        </div>
      </div>
      <div class="fieldset">
        <div class="field">
          <%= f.input :phone_number %>
        </div>
      </div>
      <div class="clear"></div>
    </div>

    <div class="lspace-t">
      <div>
        <%= image_tag 'default/user_profile.png', class: 'left title-icon' %>
        <h3><%= t('user.profile.title') %></h3>
      </div>
      <p></p>
      <div class="avatar">
        <label class="upload-button">
          <%= f.input :avatar, label: false %>
          <span class="input-button"><%= t('simple_form.file.title') %></span>
        </label>
        <div class="avatar-image">
          <%= image_tag user.avatar.url(:medium) %>
        </div>
      </div>
    </div>
    <div class="center lspace-t">
      <%= f.submit t('user.update.submit'), class: 'input-button' %>
    </div>

    <%= f.simple_fields_for :cards do |card| %>
        <%= render 'card_fields', f: card %>
    <% end %>
    <div class="links">
      <%= link_to_add_association t('card.add'), f, :cards %>
    </div>
<% end %>

app/views/users/_form_card_uid.html.erb
<%= render 'home/email_tip', email: @user.email, path: root_path %>
<div class="fields">
  <%= simple_form_for(resource, url: user_registration_path(resource), html: { 'data-url': user_check_card_path } ) do |f| %>
      <!--TODO: Handle errors-->
      <%= f.input :email, as: :hidden, value: @user.email %>
      <%= f.simple_fields_for :cards_attributes do |card_f| %>
          <%= card_f.input :uid, placeholder: t('activerecord.attributes.card.uid'), wrapper: false, label: false, input_html: { autofocus: true } %>
      <% end %>
      <%= button_tag type: :submit, class: 'ribbon button' do %>
          <%= fa_icon 'search' %>
      <% end %>
      <%= render 'general/error_popover', error: t('activerecord.errors.models.card.attributes.uid.invalid'), arrow: :up, hidden: true %>
  <% end %>
</div>

app/views/users/_form_password.html.erb
<%= render 'home/email_tip', email: @user.email, path: root_path %>
<div class="fields">
  <%= simple_form_for(resource, url: user_session_path, method: :post, html: { class: 'sign-in', 'data-url': user_check_credentials_url }) do |f| %>
      <!--TODO: Handle errors-->
      <%= f.input :email, as: :hidden, value: @user.email %>
      <%= f.input :password, placeholder: t('activerecord.attributes.user.password'), wrapper: false, label: false, input_html: { autofocus: true } %>
      <%= button_tag type: :submit, class: 'ribbon button' do %>
          <%= fa_icon 'key' %>
      <% end %>
  <% end %>
</div>
<%= render 'general/error_popover', error: t('user.errors.invalid_credentials'), arrow: :up, hidden: true %>

app/views/users/_progress_bar.html.erb
<div class="profile-progress-bar">
  <p class="desc"><%= t('user.show.completion', percentage: @user.completion_percentage) %></p>
  <div class="uk-progress-mini">
    <div class="uk-progress-bar" style="width: <%= @user.completion_percentage %>%;"></div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="full-width-weighted xlspace-t">
  <%= render 'form', user: @user %>
</div>

app/views/users/index.html.erb
<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p>
  <%= t('user.show.completion', percentage: @user.completion_percentage) %>
</p>

<ul>
  <li><%= @user.email %></li>
  <li><%= @user.first_name %></li>
  <li><%= @user.last_name %></li>
  <li><%= @user.address %></li>
  <li><%= @user.postal_code %></li>
  <li><%= @user.city %></li>
  <li><%= @user.phone_number %></li>
</ul>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>