config/routes.rb
Rails.application.routes.draw do
  put '/user_notif/:id', to: 'user_notif/notifs#read', as: :read_user_notif
  devise_for :users, controllers: { confirmations: 'users/confirmations',
                                    registrations: 'users/registrations' }

  devise_scope :user do
    patch '/confirm' => 'users/confirmations#confirm'
  end

  post '/user/preform', to: 'users#preform', as: :user_preform
  post '/user/check_cards', to: 'users#check_card', as: :user_check_card
  post '/user/check_credentials', to: 'users#check_credentials', as: :user_check_credentials

  authenticated :user do
    root to: 'locations#index', as: :authenticated_root

    post 'locations/:id/inline_update', to: 'locations#inline_update', as: :location_inline_update

    resources :locations do
      resources :offer_reductions
    end

    resources :offer_reductions
    resources :businesses
    resources :cards
    resources :users
  end

  root 'home#index', as: :root

  require 'sidekiq/web'

  # TODO: Change autorizations
  #authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  #end
end

app/models/card.rb
# A Card represent is an entity that allow the User to creates an account.
#
# It is associated to a location and keeps a track of the user activity.
#
# It is identified through a unique identifier: :uid.
class Card < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :location

  validates_uniqueness_of :uid, case_sensitive: false
  validates :uid, presence: true, format: /\A[a-zA-Z0-9]{6,}\z/

  before_create :generate_uid

  private

  # Generates a unique uid
  def generate_uid
    self.uid = loop do
      new_uid = [*('a'..'z'), *('0'..'9')].sample(6).join.upcase
      break new_uid unless Card.exists?(uid: new_uid)
    end
  end
end

app/controllers/cards_controller.rb
# Handles the requests about cards
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  # Lists all existing cards
  #
  # GET /cards
  #
  # GET /cards.json
  def index
    @cards = Card.all
  end

  # Display details of a card
  #
  # GET /cards/1
  #
  # GET /cards/1.json
  def show
  end

  # Display a form to create a new card
  #
  # GET /cards/new
  def new
    @card = Card.new
  end

  # Display a form to edit an existing card
  #
  # GET /cards/1/edit
  def edit
  end

  # Creates a new card from params
  #
  # Authorized parameters: :uid, :user_id, :location_id
  #
  # POST /cards
  #
  # POST /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # Updates an existing card from params
  #
  # Authorized parameters: :uid, :user_id, :location_id
  #
  # PATCH/PUT /cards/1
  #
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # Destroys a card
  #
  # DELETE /cards/1
  #
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Sets the card object required by the action
    def set_card
      @card = Card.find(params[:id])
    end

    # Filters the permitted params
    def card_params
      params.fetch(:card, {}).permit(:uid, :user_id, :location_id)
    end
end

app/helpers/cards_helper.rb
# Helpers relative to a Card
module CardsHelper
end

app/views/cards/_form.html.erb
<%= form_for(card) do |f| %>
  <% if card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<h1>Editing Card</h1>

<%= render 'form', card: @card %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<h1>Cards</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cards.each do |card| %>
      <tr>
        <td><%= link_to 'Show', card %></td>
        <td><%= link_to 'Edit', edit_card_path(card) %></td>
        <td><%= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Card', new_card_path %>

app/views/cards/new.html.erb
<h1>New Card</h1>

<%= render 'form', card: @card %>

<%= link_to 'Back', cards_path %>

app/views/cards/show.html.erb
<%= link_to 'Edit', edit_card_path(@card) %> |
<%= link_to 'Back', cards_path %>