config/routes.rb
Rails.application.routes.draw do
  put '/user_notif/:id', to: 'user_notif/notifs#read', as: :read_user_notif
  devise_for :users, controllers: { confirmations: 'users/confirmations',
                                    registrations: 'users/registrations' }

  devise_scope :user do
    patch '/confirm' => 'users/confirmations#confirm'
  end

  post '/user/preform', to: 'users#preform', as: :user_preform
  post '/user/check_cards', to: 'users#check_card', as: :user_check_card
  post '/user/check_credentials', to: 'users#check_credentials', as: :user_check_credentials

  authenticated :user do
    root to: 'locations#index', as: :authenticated_root

    post 'locations/:id/inline_update', to: 'locations#inline_update', as: :location_inline_update

    resources :locations do
      resources :offer_reductions
    end

    resources :offer_reductions
    resources :businesses
    resources :cards
    resources :users
  end

  root 'home#index', as: :root

  require 'sidekiq/web'

  # TODO: Change autorizations
  #authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  #end
end

app/models/location.rb
# A Location represents a real location (managed by a Business)
#
# It can have many Card and OfferReduction
class Location < ApplicationRecord
  belongs_to :business
  has_many :offer_reductions
  has_many :cards

  validates_presence_of :name, :lng, :lat
end

app/controllers/locations_controller.rb
# Handles requests about locations
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :inline_update, :destroy]

  # Lists all locations
  #
  # GET /locations
  #
  # GET /locations.json
  def index
    @locations = Location.all
  end

  # Displays details of a location
  #
  # GET /locations/1
  #
  # GET /locations/1.json
  def show
  end

  # Display a form to create a new location
  #
  # GET /locations/new
  def new
    @location = Location.new
  end

  # Display a form to edit an existing location
  #
  # GET /locations/1/edit
  def edit
  end

  # Creates a new location from params
  #
  # Authorized parameters: :business_id, :lat, :lng, :name, :formatted_name
  #
  # POST /locations
  #
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # Update an existing location from params
  #
  # Authorized parameters: :business_id, :lat, :lng, :name, :formatted_name
  #
  # PATCH/PUT /locations/1
  #
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # Updates the location from inline form
  #
  # Should only called in AJAX
  #
  # TODO: Really needed ? Maybe update can be used
  #
  # POST /locations/1/inline_update
  def inline_update
    respond_to do |format|
      if @location.update(location_params)
        format.json { render :show, status: :ok, location: @location }
      else
        format.json { render json: { error: @location.errors }, status: :ok }
      end
    end
  end

  # Destroys a location
  #
  # DELETE /locations/1
  #
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Sets the location object required by the action
  def set_location
    @location = Location.find(params[:id])
  end

  # Filters the permitted params
  def location_params
    params.fetch(:location, {}  ).permit(:business_id, :lat, :lng, :name, :formatted_name)
  end
end

app/helpers/locations_helper.rb
# Helpers relative to a Location
module LocationsHelper
end

app/views/locations/_form.html.erb
<%= form_for(location) do |f| %>
  <% if location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/_location.html.erb
<div>
  <!--<%= link_to location_offer_reductions_path(location_id: location.id) do %>-->
    <div class="location" style="background-image: url(<%= image_url('tmp/chateau_queribus.jpg') %>); background-size: cover">
      <button class="button ribbon" data-url="#">
        <%= fa_icon 'eye' %>
      </button>
      <textarea class="redactor bottom-legend" <%= "id=#{id}" if id %> name="location[formatted_name]" data-url="<%= location_inline_update_path(id: location.id, format: :json) %>">
        <%= raw location.formatted_name %>
      </textarea>
    </div>
  <!--<% end %>-->
</div>

app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<% content_for :banner do %>
    <%= render 'general/banner' %>
<% end %>

<div class="full-width-weighted center xlspace-t">
  <div class="cards-container uk-container-center uk-grid-width-1-1 uk-grid-width-xlarge-1-3 uk-grid-width-large-1-3 uk-grid-width-medium-1-3 uk-grid-width-small-1-2" data-uk-grid>
    <% titles = {} %>
    <% @locations.each_with_index do |location, i| %>
        <% titles["location-#{i}"] = location.formatted_name %>
        <%= render 'location', location: location, id: "location-#{i}" %>
    <% end %>
    <div>
      <%= link_to new_location_path do %>
          <div class="location add">
            <span>+</span>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/locations/new.html.erb
<h1>New Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>